### ISSUE TITLE
Slim down 3D Reality Bubble Memory

### ISSUE THREAD

**Issue by OrenAudeles** [OrenAudeles/Cataclysm-BN#5]
I consider this a prerequisite for #4 to work in any reasonable way

The 3D Reality Bubble is an 11x11x21 submap volume, totaling 2541 submaps. Each of these submaps is a 12x12 grid of tiles, totaling 144 tiles. Total number of tiles in the 3D Reality Bubble is **365 904**.
#### Each tile has 1 each of the following:
- Terrain ID: 4 bytes to identify what terrain is here
- Furniture ID: 4 bytes to identify what furniture is here, if any
- Luminosity: 1 byte used to count how many luminous items are in the tile (up to 255)
- Colony of Items: 80 bytes for the container to hold items with stable references, if any
  - Contains Item: 480 bytes holding all information needed to uniquely identify this item
- Field: 56 bytes for the container to hold all unique field entries in this tile, if any
  - Contains field_entry: 16 bytes holding all information needed for the lifetime of this field
- Trap ID: 4 bytes to identify what trap is here, if any
- Radiation: 4 bytes to measure how much radiation is in this tile, if any

| Per | Bytes |
| --- | ---: |
| Tile | **153 Bytes** |
| Submap | **22 032 Bytes** |
| 3D Reality Bubble | **55 983 312 Bytes** |

### Submap per-tile members
| Name | Type | Bytes (Per) | Bytes (Submap) | Bytes (3DRB) | % of Total |
| --- | :---: | ---: | ---: | ---: | ---: |
| ter | ter_id | 4 | 576 | 1 463 616 | 2.614 |
| frn | furn_id | 4 | 576 | 1 463 616 | 2.614 |
| lum | uint8_t | 1 | 144 | 365 904 | 0.654 |
| itm | cata::colony<item> | 80 | 11 520 | 29 272 320 | 52.288 |
| fld | field | 56 | 8 064 | 20 490 624 | 36.601 |
| trp | trap_id | 4 | 576 | 1 463 616 | 2.614 |
| rad | int | 4 | 576 | 1 463 616 | 2.614 |

#### Usage and Density of Submap Data
| Data | Usage / Density Note |
| --- | --- |
| Terrain | Always around, very dense |
| Furniture | Sparse in most cases, queried a lot |
| Luminosity | Used when generating lightmap from luminous items |
| Items | Sparse in most cases, queried a lot. Player areas generally have a lot of items |
| Fields | Sparse, but has weird processing |
| Trap | Very Sparse |
| Radiation | Pretty sparse, most areas are not radioactive |

#### What can I do?
| Data | Options |
| --- | --- |
| Terrain | Nothing. Terrain is omnipresent. Only way it could be discarded is if we really don't need terrain, such as in some tests |
| Furniture | Probably Reality Bubble scale `std::map`. Won't be O(1) access / modification but that can be worked around |
| Luminosity | Only need a value in locations items exist |
| Items | Reality Bubble scale `std::map` containing colonies at positions? |
| Fields | No idea. Considering they're the second highest memory consumer there needs to be a solution |
| Trap | Reality Bubble scale `std::map`. Again won't be O(1) access / modification but it'll be a small map |
| Radiation | Same as traps. It's not going to be dense in most cases |

#### Task List
- [ ] Slim down Furnitures
- [ ] Slim down Items / Luminosity
- [ ] Slim down Fields
- [ ] Slim down Traps
- [ ] Slim down Radiation

**Comment by OrenAudeles** [comment]
Instead of going the `std::map` route might be easier to just lazily allocate each of these. If nothing is set then it's some default value. If it gets set then we go ahead and allocate the grid. Can then periodically run through submaps to check if they've been emptied out. No Items in the submap? No need to allocate item space. No fields? No allocate! This would be a much easier change to implement since it doesn't have as many moving parts, and immediately takes care of the number one issue of Uniform Submaps (all air, all rock terrains) using a bunch of memory unnecessarily. If there are no tall buildings nor underground structures we'd immediately remove `11x11x20` submaps worth of everything but terrain, and even the terrain we might not need in that case. If we can remove all of that we'd decrease memory footprint of 3D Reality Bubble down to around 5% of current, or to somewhere around 2.6MB from almost 56MB. Memory would be used where things exist, and freed eventually if nothing exists anymore. 2.6MB is best case for the reality bubble, and is likely to require more but not significantly more memory.
